### ISSUE TITLE
Usage help: Search and replace

### ISSUE THREAD

**Issue by artm69** [LenShustek/Eudora_fix_mbx#2]
Hello. I'd like to do the following with your script:

1. I have an incoming email that I transfer to z.mbx.

2. This email contains this string:
    http://www.moxieproxy.com/ebay.php?site=US&id=

3. I'd like to replace it with this:
    https://www.ebay.com/itm/

I believe I can I do this with your script. Can you advise how?

**Comment by LenShustek** [comment]
If it is that specific replacement you want to make, then in theory it's easy: just add the appropriate "search" = "replace" line in the translations.txt file.
The complication is that because the ampersand is a special escape character in HTML, it actually appears in the mailbox as an ampersand followed by "amp;".  So the line you want to add is this:
"http://www.moxieproxy.com/ebay.php?site=US&amp;id=" = "https://www.ebay.com/itm/"

**Comment by artm69** [comment]
The regular "&" worked fine, the "&amp;" did not.

I'm now working on a batch file to handle mbx's in subfolders.


At 06:11 PM 1/21/2022, you wrote:

>If it is that specific replacement you want to make, then in theory 
>it's easy: just add the appropriate "search" = "replace" line in the 
>translations.txt file.
>The complication is that because the ampersand is a special escape 
>character in HTML, it actually appears in the mailbox as an 
>ampersand followed by "amp;". So the line you want to add is this:
>"<http://www.moxieproxy.com/ebay.php?site=US&amp;id=>http://www.moxieproxy.com/ebay.php?site=US&amp;id=" 
>= "https://www.ebay.com/itm/"
>
